services:
  db:
    image: mysql:8.0
    container_name: task_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_management_development
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: task_rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: