name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.10
          bundler-cache: true
      - run: bin/brakeman --no-pager
      - run: bin/bundler-audit

  scan_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.10
          bundler-cache: true
      - run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.10
          bundler-cache: true

      - name: Show Ruby version
        run: ruby -v

      - name: Show Rubocop version
        run: bundle exec rubocop -V

      - name: Run Rubocop
        run: bin/rubocop

  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: task_management_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.10
          bundler-cache: true

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y default-libmysqlclient-dev

      - name: Run Tests
        env:
          RAILS_ENV: test
          DB_HOST: mysql
        run: |
          bin/rails db:prepare
          bin/rails test

  system-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: task_management_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.10
          bundler-cache: true

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y default-libmysqlclient-dev

      - name: Run System Tests
        env:
          RAILS_ENV: test
          DB_HOST: mysql
        run: |
          bin/rails db:prepare
          bin/rails test:system

      - name: Upload screenshots if failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: tmp/screenshots
          if-no-files-found: ignore